@host = http://127.0.0.1:8081
@token =

### Регистрация пользователя
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "f1try37",
  "password": "testpassword123"
}

### Логин
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "f1try37",
  "password": "testpassword123"
}

> {%
    client.global.set("token", response.body.token);
%}

### Создать привычку
POST {{host}}/api/habits
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Учиться",
  "description": "по 2 часа в день"
}

### Получить список привычек
GET {{host}}/api/habits
Authorization: Bearer {{token}}

### Привычка по id
GET {{host}}/api/habits/1
Authorization: Bearer {{token}}

### Несуществующая привычка
GET {{host}}/api/habits/999
Authorization: Bearer {{token}}

### Невалидная привычка
POST {{host}}/api/habits
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "",
  "description": "тест"
}

### Обновление привычки
PUT {{host}}/api/habits/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Читать книги",
  "description": "50 страниц"
}

### Удаление привычки
DELETE {{host}}/api/habits/4
Authorization: Bearer {{token}}

### Удаление несуществующей привычки
DELETE {{host}}/api/habits/999
Authorization: Bearer {{token}}

### Отметить привычку выполненной
POST {{host}}/api/habits/2/entries
Authorization: Bearer {{token}}

### Отметить несуществующую привычку выполненной
POST {{host}}/api/habits/999/entries
Authorization: Bearer {{token}}

### Запрос без токена — должен вернуть 401
GET {{host}}/api/habits